label: Product Recommendations
pages:
- label: Product Recommendations
  url: /recommendations/product-recs.html
  versionless: true

- label: Configure Recommendations
  url: /recommendations/configure.html
  versionless: true

- label: Recommendation Events
  url: /recommendations/events.html
  versionless: true

- label: Verify Event Collection
  url: /recommendations/verify.html
  versionless: true

- label: Test Recommendations
  url: /recommendations/test.html
  versionless: true

- label: Troubleshoot Recommendations
  url: /recommendations/troubleshooting.html
  versionless: true

- label: Customize Recommendations
  url: /recommendations/customize.html
  versionless: true

- label: Recommendations SDK
  url: /recommendations/recs-api.html
  versionless: true

- label: Get Support
  url: /recommendations/support.html
  versionless: true