# -*- mode: ruby -*-
# vi: set ft=ruby :

HOST_NAME  = "devdocs.magento.vg"
RAM = "1024"
HOST_PORT = "4000"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.hostname = HOST_NAME
  config.vm.network :forwarded_port, guest: 4000, host: HOST_PORT
  config.vm.synced_folder "../.", "/jekyll/devdocs"
  config.vm.provider "virtualbox" do |v|
    v.customize ['modifyvm', :id, '--name', HOST_NAME, '--memory', RAM]
  end
end