---
title: Magento_ProductAlert
source_repo: magento2ce
release: 2.4.1
github_path: app/code/Magento/ProductAlert/README.md
last_modified_at: '2014-10-31 09:04:08 -0700'
content: The Magento_ProductAlert module enables product alerts, which allow customers
  to sign up for emails about product price or stock status change.
