---
title: InventoryConfigurableProductAdminUi
content: |-
  The `InventoryConfigurableProductAdminUi`extends the Magento Admin UI to add inventory management functionality.

  This module is part of the new inventory infrastructure. The
  [Inventory Management overview](https://devdocs.magento.com/guides/v2.4/inventory/index.html)
  describes the MSI (Multi-Source Inventory) project in more detail.

  ## Installation details

  This module is installed as part of Magento Open Source. It may be disabled if the Inventory Management UI
  is provided by a 3rd-party system or if you run a headless version of Magento.

  ## Extensibility

  The `InventoryConfigurableProductAdminUi` module contains several extension points.

  ### UI Components

  The `view/adminhtml/ui_component` directory contains extensible UI components.
