---
title: CatalogRuleConfigurable
content: Magento_CatalogRuleConfigurable module is an extension of Magento_CatalogRule
  and Magento_ConfigurableProduct modules that handle catalog rule indexer for configurable
  product
