---
title: QuoteConfigurableOptions
content: |-
  This module provides data provider for creating buy request for configurable products.

  ## Installation

  This module does not introduce any database schema modifications or new data.

  For information about a module installation in Magento 2, see [Enable or disable modules](https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-subcommands-enable.html).

  ## Extensibility

  Extension developers can interact with the Magento_QuoteConfigurableOptions module. For more information about the Magento extension mechanism, see [Magento plug-ins](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/plugins.html).

  [The Magento dependency injection mechanism](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/depend-inj.html) enables you to override the functionality of the Magento_QuoteConfigurableOptions module.
