---
title: Magento_ConfigurableRequisitionListGraphQl
source_repo: magento2b2b
release: 1.3.1
github_path: app/code/Magento/ConfigurableRequisitionListGraphQl/README.md
last_modified_at: '2020-12-01 20:29:10 +0530'
content: "**ConfigurableRequisitionListGraphQl** provides GraphQL schema and resolvers
  for the requisition list module to extend and implement configurable products in
  requisition list"
