---
title: Magento_Config
source_repo: magento2ce
release: 2.3.3
github_path: app/code/Magento/Config/README.md
last_modified_at: '2015-02-24 11:30:51 -0600'
content: "#Config\nThe Config module is designed to implement system configuration
  functionality.\nIt provides mechanisms to add, edit, store and retrieve the configuration
  data\nfor each scope (there can be a default scope as well as scopes for each website
  and store).\n\nModules can add items to be configured on the system configuration
  page by creating \nsystem.xml files in their etc/adminhtml directories. These system.xml
  files get merged \nto populate the forms in the config page.\n"
