---
title: Magento_ConfigurableProductGraphQl
edition: ce
last_modified_at: '2018-01-16 13:17:37 -0600'
content: |
  **ConfigurableProductGraphQl** provides type and resolver information for the GraphQl module
  to generate configurable product information.
