---
title: Magento_ConfigurableProduct
edition: ce
last_modified_at: '2014-12-12 12:14:06 -0800'
content: |
  Magento_ConfigurableProduct module introduces new product type in the Magento application called Configurable Product.
  This module is designed to extend existing functionality of Magento_Catalog module by adding new product type.

  Configurable Products let the customers select the variant they desire by choosing options.
  For example, store owner sells t-shirts in two colors and three sizes.
