---
title: Magento_ProductAlert
edition: ce
content: 'The Magento_ProductAlert module enables product alerts, which allow customers
  to sign up for emails about product price or stock status change.

  '
last_modified_at: '2014-10-31 09:04:08 -0700'
